# Generated by Django 5.1.4 on 2025-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=250)),
                ('on_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['on_create'],
            },
        ),
    ]
