# Generated by Django 5.1.4 on 2025-01-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterings', '0002_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
    ]
