# Generated by Django 5.1.4 on 2025-01-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterings', '0003_sub_district_alter_district_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, max_length=55, null=True),
        ),
    ]
