# Generated by Django 5.1.4 on 2025-02-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterings', '0004_specialization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
