# Generated by Django 5.1.4 on 2025-01-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital', 'Hospital')], max_length=10, null=True),
        ),
    ]
