# Generated by Django 5.1.4 on 2025-01-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctor_hospital_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certificate_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='number_of_departments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
