# Generated by Django 5.1.4 on 2025-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_profile_image_patient_height_ft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/defalut.png', null=True, upload_to='profile_images/'),
        ),
    ]
