# Generated by Django 5.1.4 on 2025-01-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height_ft',
            field=models.CharField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height_in',
            field=models.CharField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight_kg',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
