# Generated by Django 5.1.4 on 2025-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='height_in',
        ),
        migrations.AlterField(
            model_name='patient',
            name='height_ft',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
