# Generated by Django 5.1.4 on 2025-01-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patient_height_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='degree_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='BMDC_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degrees',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
