# Generated by Django 5.1.4 on 2025-01-17 01:50

import accounts.models
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_doctor_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='biography',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Meeting link (Zoom or Google Meet only)', max_length=500, null=True, validators=[accounts.models.validate_meeting_link]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient_checked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=27, null=True),
        ),
    ]
