# Generated by Django 5.1.4 on 2025-01-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_doctor_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='next_verification',
            field=models.BooleanField(default=False),
        ),
    ]
