# Generated by Django 5.1.4 on 2025-01-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_doctor_next_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_report',
        ),
    ]
