# Generated by Django 5.1.4 on 2025-01-19 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_patient_medical_report'),
        ('filterings', '0003_sub_district_alter_district_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterings.specialization'),
        ),
    ]
