# Generated by Django 5.1.4 on 2025-01-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_doctor_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_days',
        ),
    ]
