# Generated by Django 5.1.4 on 2025-01-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_doctor_working_days'),
        ('filterings', '0003_sub_district_alter_district_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterings.district'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterings.sub_district'),
        ),
    ]
