# Generated by Django 5.1.4 on 2025-01-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_doctor_district_doctor_region_doctor_sub_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient_checked',
        ),
    ]
