# Generated by Django 5.1.4 on 2025-02-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_doctor_patient_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, default='https://i.ibb.co.com/0R4xM5rk/default.png', max_length=500, null=True),
        ),
    ]
