# Generated by Django 5.1.4 on 2025-03-14 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_viewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='user',
        ),
        migrations.AddField(
            model_name='viewcount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
