# Generated by Django 5.1.4 on 2025-03-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_viewcount_ip_address_remove_viewcount_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='current_balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='total_appointments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='total_comments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='total_earned',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
