# Generated by Django 5.1.4 on 2026-06-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_doctor_current_balance_doctor_total_appointments_and_more'),
        ('filterings', '0005_healthconcern'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['next_verification'], name='accounts_do_next_ve_5ebfe6_idx'),
        ),
    ]
