# Generated by Django 5.1.4 on 2025-01-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_appointment_medical_report_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='medical_report',
            field=models.FileField(blank=True, help_text='Upload any previous report or prescriptions if you have. ( Maximum file size 2MB, pdf only)', null=True, upload_to='medical_reports/'),
        ),
    ]
