# Generated by Django 5.1.4 on 2025-02-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medical_report',
        ),
    ]
