# Generated by Django 5.1.4 on 2025-02-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_doctor_fee_doctor_health_concern'),
        ('doctors', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='accounts.patient'),
        ),
    ]
